#!/usr/bin/env python3

import pickle

from mv.tensormethod.contract import invariants
from mv.tensormethod.parse_hs import parse, H9_LNV_NF3, H11_LNV_NF3
from mv.tensormethod.utils import is_linear_in_deriv

# write out data as pickled dictionary of string label to Operator
save_data = True

# parsed_hs = parse(H9_LNV_NF3)
parsed_hs = parse(H11_LNV_NF3)

out_dict = {}
counter = 1
for fields in parsed_hs:
    breakpoint()
    if not is_linear_in_deriv(fields):
        print("Not linear")
        continue

    invs = invariants(*fields)
    if not invs:
        print("No invariants")
        continue

    print(f"Invariants for operator {counter}:")
    for inv in invs:
        print(f"{counter} & {inv.latex()}")
        if save_data:
            out_dict[str(counter)] = inv.pickle_form()

    print("\n")
    counter += 1

if save_data:
    # pickle data
    filename = "deriv_operators.p"
    with open(filename, "wb+") as out:
        pickle.dump(out_dict, out)
