#!/usr/bin/env python3

import pickle

from mv.tensormethod.contract import invariants
from mv.tensormethod.parse_hs import parse, H9_LNV_NF3, H11_LNV_NF3
from mv.tensormethod.utils import is_linear_in_deriv, is_fieldstrength_in

from string import ascii_lowercase

# write out data as pickled dictionary of string label to Operator
save_data = True

parsed_hs = parse(H9_LNV_NF3)
# parsed_hs = parse(H11_LNV_NF3)

out_dict = {}
counter = 1
for fields in parsed_hs:
    # if not is_linear_in_deriv(fields):
    # print("Not linear")
    # continue
    # if counter == 46:
    #     breakpoint()
    if is_fieldstrength_in(fields):
        continue

    invs = invariants(*fields)
    if not invs:
        # print("No invariants")
        continue

    print(f"Invariants for operator {counter}:")
    for i, inv in enumerate(invs):
        label = str(counter) + (ascii_lowercase[i] if len(invs) > 1 else "")
        print(f"${label}$ & ${inv.latex(ignore=['c', 'u', 'd'])}$ \\\\")
        if save_data:
            out_dict[label] = inv.pickle_form()

    print("\n")
    counter += 1

if save_data:
    # pickle data
    filename = "deriv_operators.p"
    with open(filename, "wb+") as out:
        pickle.dump(out_dict, out)
