#!/usr/bin/env python3

"""Script to print SU(2) structures of operators in ΔL = 2 SMEFT up to dimension
11.

"""

from contract import invariants
from lnv import BL_LIST
from sm import *

for k, v in BL_LIST.items():
    invs = invariants(*[eval(f) for f in k])
    print(f"Invariants for operator {v}:")
    for inv in invs:
        print(inv.latex())
    print(
        "--------------------------------------------------------------------------------\n"
    )
